# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-t0-crs"
BBFILE_PATTERN_meta-t0-crs = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-t0-crs = "6"

LAYERDEPENDS_meta-t0-crs = "core"
LAYERSERIES_COMPAT_meta-t0-crs = "scarthgap"
