#!/usr/bin/env bash

# This is the "real" post-receive hook that gets installed in
# hooks/post-receive. It is responsible for executing other hooks in this
# directory, and is not useful on its own. See README for details.

GIT_DIR=$(dirname "$0")/..

# Check prerequisites
if ! command -v tmux &> /dev/null
then
	echo "ERROR: tmux is not installed. It's an essential prerequisite."
	exit
fi

while read oldrev newrev refname
do
HOOK="$(echo "$refname" | rev | cut -d/ -f1 | rev)"
SESSION="$HOOK-$newrev"
echo Creating tmux session $SESSION
TMP=$(mktemp /tmp/pr-hook.XXXXXX) \
	&& git --git-dir="$GIT_DIR" show "$newrev":"hooks/$HOOK" > "$TMP" \
	&& chmod +x "$TMP" \
	&& tmux new-session -d -s "$SESSION" "\"$TMP\" \"$oldrev\" \"$newrev\" \"$refname\""
done
