#!/usr/bin/env bash

oldrev="$1"
newrev="$2"
refname="$3"

WORKTREE=autobuild/$newrev-$(echo "$refname" | rev | cut -d/ -f1 | rev)
echo "Work tree: $WORKTREE"
if ! git worktree add -d "$WORKTREE" "$newrev"
then
	echo "ERROR: git worktree failed."
	exit
fi

unset GIT_DIR  # figure it out yourself
cd "$WORKTREE"
echo "Autobuild: working directory is $(pwd)"

make rootfs
